[versions]
jackson = "2.15.0"
junit = "5.9.1"
lombok = "1.18.26"
mockserver = "5.15.0"
testcontainers = "1.18.0"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

# Test containers
mockserver-client = { module = "org.mock-server:mockserver-client-java", version.ref = "mockserver" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-mockserver = { module = "org.testcontainers:mockserver", version.ref = "testcontainers" }
