name: Gradle Build

on:
  push:

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Run gradle build
        run: ./gradlew build
